import "server-only";
import { testHooksEnabled } from "@/lib/env/test-hooks";

/**
 * A one-shot fault for the end-to-end specs, and nothing else (M8-03, M8-04): "the next database
 * read of this tenant page fails". A page generated by a production server is cached, and a Postgres
 * outage cannot be arranged for one request from a Playwright test, so a spec arms a fault for one
 * handle (or one page id) with `GET /hl-fail-next-read` on a tenant host and the next read for that
 * handle in `published-page.ts` throws once. It is keyed, so specs running side by side in one server
 * cannot fail each other's pages.
 *
 * It exists only when the server runs with HYDLNK_QUERY_COUNTER=1, the test flag that already turns
 * on `GET /hl-query-count` and is never set in production, and never on a Vercel production
 * deployment even if it were (`testHooksEnabled`): with the hook off `armFailNextRead` does nothing
 * and `failIfArmed` never throws, so the set of armed keys cannot grow there either. The set lives on globalThis so the route that arms it
 * and the page render that consumes it share it within one process.
 */
const KEY = "__hydlnkFailNextRead";
const store = globalThis as typeof globalThis & { [KEY]?: Set<string> };

export type FaultTarget = { handle: string } | { pageId: string };

const keyOf = (target: FaultTarget) =>
  "handle" in target ? `handle:${target.handle}` : `page:${target.pageId}`;

export function faultInjectionEnabled(): boolean {
  return testHooksEnabled();
}

/** Arms (or, with `armed: false`, disarms) a failure of the next read for `target`. False when the hook is off. */
export function armFailNextRead(target: FaultTarget, armed = true): boolean {
  if (!faultInjectionEnabled()) return false;
  const faults = (store[KEY] ??= new Set());
  if (armed) faults.add(keyOf(target));
  else faults.delete(keyOf(target));
  return true;
}

/** Throws once, right before a tenant page's database read, when a spec armed it for this handle or page. */
export function failIfArmed(target: FaultTarget): void {
  if (!faultInjectionEnabled() || !store[KEY]?.delete(keyOf(target))) return;
  throw new Error("Injected failure: the database is unreachable");
}
