import { createHash } from "node:crypto";
import { TENANT_ASSET_PREFIX } from "./constants";

/**
 * Build-time helpers for the one tenant script (M8-05). Not imported by anything that runs in a
 * request: `scripts/build-tenant-assets.ts` writes the hashed file and `generated.ts` with them,
 * and tests/unit/m8-assets-script-build.test.ts recomputes the same values to fail on a stale build.
 *
 * The "build" is deliberately tiny: the readable source is plain browser JavaScript, so all it does
 * is drop comment-only lines and indentation (the source keeps comments on their own lines for
 * exactly this reason) and name the file after the hash of the result.
 */

export interface BuiltScript {
  /** What is written to `public/_t/{file}`. */
  code: string;
  /** First 12 hex characters of the SHA-256 of `code`. */
  hash: string;
  /** `p.{hash}.js` */
  file: string;
  /** `/_t/p.{hash}.js` */
  src: string;
  /** Subresource Integrity value of `code` (`sha384-...`). */
  integrity: string;
}

/**
 * Drops block comments and comment-only lines, indentation and blank lines. Code lines are kept
 * as they are (so no ASI hazards), and a code line is never given a trailing comment: the builder
 * refuses a source that has one, because the line-based strip could not tell it from a string.
 */
export function stripScript(source: string): string {
  const withoutBlocks = source.replace(/\/\*[\s\S]*?\*\//g, "");
  const lines: string[] = [];
  for (const raw of withoutBlocks.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("//")) continue;
    if (/\s\/\/\s/.test(line)) {
      throw new Error(`Put comments on their own lines in the tenant script: ${line}`);
    }
    lines.push(line);
  }
  return `${lines.join("\n")}\n`;
}

export function buildTenantScript(source: string): BuiltScript {
  const code = stripScript(source);
  const hash = createHash("sha256").update(code).digest("hex").slice(0, 12);
  const file = `p.${hash}.js`;
  return {
    code,
    hash,
    file,
    src: `${TENANT_ASSET_PREFIX}/${file}`,
    integrity: `sha384-${createHash("sha384").update(code).digest("base64")}`,
  };
}

/** The source of `src/lib/tenant-assets/generated.ts`: three constants, nothing else. */
export function generatedModuleSource(built: BuiltScript): string {
  return `/*
 * Generated by scripts/build-tenant-assets.ts from script/tenant.js. Do not edit by hand: run
 * \`pnpm tenant-assets\`. tests/unit/m8-assets-script-build.test.ts fails when this file or
 * public${TENANT_ASSET_PREFIX}/${"{file}"} is missing or stale.
 */
export const TENANT_SCRIPT_FILE = "${built.file}";
export const TENANT_SCRIPT_SRC = "${built.src}";
export const TENANT_SCRIPT_INTEGRITY = "${built.integrity}";
`;
}
