/*
 * Generated by scripts/build-tenant-assets.ts from script/tenant.js. Do not edit by hand: run
 * `pnpm tenant-assets`. tests/unit/m8-assets-script-build.test.ts fails when this file or
 * public/_t/{file} is missing or stale.
 */
export const TENANT_SCRIPT_FILE = "p.28f7e9af53f9.js";
export const TENANT_SCRIPT_SRC = "/_t/p.28f7e9af53f9.js";
export const TENANT_SCRIPT_INTEGRITY = "sha384-Vus3Va0NtxEHoE3Y//TCjnWvquq6EPSBNbYcAYoIYf6gJqNoTHkrjEG2a3sALJkj";
