/**
 * The page document: one module for the schemas, limits, ids, URL rules, embed parsing, block
 * defaults and the publish form. The editor, the Publish action and the public-page query all
 * import from here; nothing else defines the document shape.
 */
export {
  BLOCK_TYPES,
  BLOCK_TYPE_LABELS,
  IMAGE_PATH_PATTERN,
  SOCIAL_PLATFORMS,
  SOCIAL_PLATFORM_LABELS,
  blockSchema,
  draftDocSchema,
  imageRefSchema,
  publishBlockSchema,
  publishDocSchema,
  publishedDocSchema,
  stripHiddenCharacters,
  type Block,
  type BlockType,
  type CardBlock,
  type DividerBlock,
  type DocTheme,
  type DraftDoc,
  type EmbedBlock,
  type GridBlock,
  type GridCell,
  type HeaderBlock,
  type ImageBlock,
  type ImageRef,
  type LinkBlock,
  type Profile,
  type Share,
  type PublishDoc,
  type SocialBlock,
  type SocialIcon,
  type SocialPlatform,
  type SocialWebPlatform,
  type TextBlock,
} from "./schema";
export { LIMITS, codePointLength, singleLine, truncateToCodePoints } from "./limits";
export {
  SHARE_IMAGE_MIN_WIDTH,
  SHARE_IMAGE_WIDTH_MESSAGE,
  isShareEmpty,
  publishShare,
  publishShareImage,
  shareDescriptionOf,
  shareTitleOf,
} from "./share";
export {
  PHOTO_BORDERS,
  PHOTO_SHAPES,
  PHOTO_SIZES,
  PHOTO_SIZE_PX,
  PROFILE_OPTION_DEFAULTS,
  PROFILE_OPTION_KEYS,
  PROFILE_OPTION_MESSAGES,
  applyProfileOption,
  isProfileOptionValue,
  pickOption,
  resolveProfileOptions,
  type PhotoBorder,
  type PhotoShape,
  type PhotoSize,
  type ProfileOptionChange,
  type ProfileOptionKey,
  type ProfileOptions,
} from "./profile-options";
export { BLOCK_ID_PATTERN, newBlockId } from "./ids";
export {
  EMAIL_ERROR_MESSAGE,
  MAX_EMAIL_LENGTH,
  MAX_URL_LENGTH,
  URL_ERROR_MESSAGE,
  emailAddress,
  httpUrl,
  isEmailAddress,
  isHttpUrl,
  mailtoHref,
  normalizeUrl,
  safeHref,
} from "./url";
export {
  EMBED_BAR_HEIGHT,
  EMBED_ERROR_MESSAGE,
  EMBED_HEIGHTS,
  EMBED_PROVIDER_NAMES,
  EMBED_SHORT_LINK_MESSAGE,
  TWITCH_PARENT_PATTERN,
  embedAllow,
  embedAllowsFullscreen,
  embedErrorMessage,
  embedFacadeHeight,
  embedHeight,
  embedLabel,
  embedPlayLabel,
  embedPlayerSrc,
  embedPlayerTitle,
  hasFixedHeight,
  isEmbedShortLink,
  parseEmbed,
  type EmbedKind,
  type EmbedProvider,
  type ParsedEmbed,
  type SpotifyKind,
} from "./embed";
export {
  blockDefaults,
  changeSocialPlatform,
  emptyDraft,
  newGridCell,
  newSocialIcon,
} from "./defaults";
export {
  collectImageRefs,
  collectPublishErrors,
  publishFormsEqual,
  toPublishForm,
  type PublishError,
} from "./publish";
export {
  FEATURED_LIMIT_MESSAGE,
  LINK_FEATURED,
  LINK_FEATURED_LABELS,
  LINK_FEATURED_VALUE_MESSAGE,
  LINK_ICONS,
  LINK_ICON_ERROR_MESSAGE,
  LINK_ICON_LABELS,
  LINK_THUMB_UPLOAD_KIND,
  featuredOverLimit,
  isLinkFeatured,
  isLinkIconName,
  type LinkFeatured,
  type LinkIconName,
} from "./link-icons";
export {
  CARD_BANNER_RATIO,
  FOCUS_MESSAGE,
  IMAGE_SHAPES,
  IMAGE_SHAPE_MESSAGE,
  IMAGE_SHAPE_RATIO,
  focusOf,
  focusSchema,
  isCenterFocus,
  objectPositionOf,
  pickShape,
  publishFocus,
  roundFocus,
  type Focus,
  type ImageShape,
} from "./focus";
export {
  MARK_MESSAGES,
  clipMarks,
  linkMarksOf,
  publishTextAndMarks,
  sortMarks,
  textSegments,
  type BoldMark,
  type ItalicMark,
  type LinkMark,
  type Mark,
  type TextSegment,
} from "./marks";
export {
  addLinkMark,
  adjustMarks,
  isFormatted,
  linkAt,
  linksOverlapping,
  removeLinkMark,
  setLinkUrl,
  textBetween,
  toCodePointOffset,
  toUtf16Index,
  toggleFormat,
  type FormatType,
} from "./marks-edit";
