/**
 * The page document: one module for the schemas, limits, ids, URL rules, embed parsing, block
 * defaults and the publish form. The editor, the Publish action and the public-page query all
 * import from here; nothing else defines the document shape.
 */
export {
  BLOCK_TYPES,
  BLOCK_TYPE_LABELS,
  IMAGE_PATH_PATTERN,
  SOCIAL_PLATFORMS,
  SOCIAL_PLATFORM_LABELS,
  blockSchema,
  draftDocSchema,
  imageRefSchema,
  publishBlockSchema,
  publishDocSchema,
  publishedDocSchema,
  stripHiddenCharacters,
  type Banner,
  type Block,
  type BlockType,
  type CardBlock,
  type ContactBlock,
  type AppLink,
  type AppsBlock,
  type BookBlock,
  type BookLink,
  type DiscountBlock,
  type MapBlock,
  type DividerBlock,
  type DocTheme,
  type DraftDoc,
  type EmbedBlock,
  type FaqBlock,
  type FaqItem,
  type GridBlock,
  type GridCell,
  type HeaderBlock,
  type ImageBlock,
  type ImageRef,
  type LinkBlock,
  type Profile,
  type Share,
  type PublishDoc,
  type SocialBlock,
  type SocialIcon,
  type SocialPlatform,
  type SocialWebPlatform,
  type TextBlock,
} from "./schema";
export { LIMITS, codePointLength, singleLine, truncateToCodePoints } from "./limits";
export {
  APP_STORES,
  APP_STORE_LABELS,
  APP_STORE_MESSAGE,
  BOOK_STORES,
  BOOK_STORE_LABELS,
  BOOK_STORE_MESSAGE,
  STORE_DUPLICATE_MESSAGE,
  STORE_MISSING_MESSAGE,
  appBadgeWords,
  appStoreLabel,
  appStoresLimitMessage,
  bookStoreLabel,
  bookStoresLimitMessage,
  isAppStore,
  isBookStore,
  type AppBadgeWords,
  type AppStore,
  type BookStore,
} from "./stores";
export { mapQuery, mapTargets, type MapTargets } from "./map";
export {
  BANNER_MESSAGES,
  LOGO_HEIGHT_EM,
  LOGO_PLACEMENTS,
  LOGO_PLACEMENT_DEFAULT,
  LOGO_PLACEMENT_LABELS,
  NAME_SIZES,
  NAME_SIZE_DEFAULT,
  NAME_SIZE_LABELS,
  NAME_SIZE_SCALE,
  PROFILE_STYLE_KEYS,
  PROFILE_STYLE_MESSAGES,
  bannerIssues,
  isBannerEmpty,
  nameFontStack,
  pickLogoPlacement,
  pickNameFont,
  pickNameSize,
  pickProfileStyle,
  publishBanner,
  publishNameStyle,
  resolveNameStyle,
  type BannerField,
  type BannerLike,
  type LogoPlacement,
  type NameSize,
  type NameStyle,
} from "./page-extras";
export {
  SHARE_IMAGE_MIN_WIDTH,
  SHARE_IMAGE_WIDTH_MESSAGE,
  isShareEmpty,
  publishShare,
  publishShareImage,
  shareDescriptionOf,
  shareTitleOf,
} from "./share";
export {
  PHOTO_BORDERS,
  PHOTO_SHAPES,
  PHOTO_SIZES,
  PHOTO_SIZE_PX,
  PROFILE_OPTION_DEFAULTS,
  PROFILE_OPTION_KEYS,
  PROFILE_OPTION_MESSAGES,
  applyProfileOption,
  isProfileOptionValue,
  pickOption,
  resolveProfileOptions,
  type PhotoBorder,
  type PhotoShape,
  type PhotoSize,
  type ProfileOptionChange,
  type ProfileOptionKey,
  type ProfileOptions,
} from "./profile-options";
export { BLOCK_ID_PATTERN, newBlockId } from "./ids";
export {
  EMAIL_ERROR_MESSAGE,
  MAX_EMAIL_LENGTH,
  MAX_URL_LENGTH,
  URL_ERROR_MESSAGE,
  PHONE_ERROR_MESSAGE,
  emailAddress,
  httpUrl,
  isEmailAddress,
  isHttpUrl,
  isPhoneNumber,
  mailtoHref,
  normalizeUrl,
  safeHref,
  telHref,
} from "./url";
export {
  EMBED_BAR_HEIGHT,
  EMBED_ERROR_MESSAGE,
  EMBED_HEIGHTS,
  EMBED_PROVIDER_NAMES,
  EMBED_SHORT_LINK_MESSAGE,
  TWITCH_PARENT_PATTERN,
  embedAllow,
  embedAllowsFullscreen,
  embedErrorMessage,
  embedFacadeHeight,
  embedHeight,
  embedLabel,
  embedPlayLabel,
  embedPlayerSrc,
  embedPlayerTitle,
  hasFixedHeight,
  isEmbedShortLink,
  parseEmbed,
  type EmbedKind,
  type EmbedProvider,
  type ParsedEmbed,
  type SpotifyKind,
} from "./embed";
export {
  blockDefaults,
  changeSocialPlatform,
  emptyDraft,
  newAppLink,
  newBookLink,
  newFaqItem,
  newGridCell,
  newSocialIcon,
} from "./defaults";
export {
  collectImageRefs,
  collectPublishErrors,
  publishFormsEqual,
  toPublishForm,
  type PublishError,
} from "./publish";
export {
  FEATURED_LIMIT_MESSAGE,
  LINK_FEATURED,
  LINK_FEATURED_LABELS,
  LINK_FEATURED_VALUE_MESSAGE,
  LINK_ICONS,
  LINK_ICON_ERROR_MESSAGE,
  LINK_ICON_LABELS,
  LINK_THUMB_UPLOAD_KIND,
  featuredOverLimit,
  isLinkFeatured,
  isLinkIconName,
  type LinkFeatured,
  type LinkIconName,
} from "./link-icons";
export {
  CARD_BANNER_RATIO,
  FOCUS_MESSAGE,
  IMAGE_SHAPES,
  IMAGE_SHAPE_MESSAGE,
  IMAGE_SHAPE_RATIO,
  focusOf,
  focusSchema,
  isCenterFocus,
  objectPositionOf,
  pickShape,
  publishFocus,
  roundFocus,
  type Focus,
  type ImageShape,
} from "./focus";
export {
  ALIGN_VALUES,
  MARK_MESSAGES,
  alignMarksOf,
  clipMarks,
  isAlignMark,
  isAlignValue,
  linkMarksOf,
  publishTextAndMarks,
  salvageMarks,
  sortMarks,
  textLines,
  textSegments,
  type AlignMark,
  type AlignValue,
  type BoldMark,
  type InlineMark,
  type ItalicMark,
  type LinkMark,
  type Mark,
  type StrikeMark,
  type TextLine,
  type TextSegment,
  type UnderlineMark,
} from "./marks";
export { linkAt, linksOverlapping, textBetween } from "./marks-edit";
// Wave K link tags, link lock and redirect mode (M9-27 .. M9-32).
export {
  UTM_DRAFT_MAX,
  UTM_EXAMPLE_URL,
  UTM_KEYS,
  UTM_LABELS,
  UTM_LENGTH_MESSAGE,
  UTM_PARAM,
  UTM_PATTERN_MESSAGE,
  UTM_PLACEHOLDERS,
  UTM_VALUE_MAX,
  hasCustomUtm,
  publishLinkUtm,
  publishPageUtm,
  utmExample,
  utmValueError,
  validUtmValue,
  withUtm,
  type LinkUtm,
  type PageUtm,
  type UtmKey,
} from "./utm";
export {
  LOCK_CODE_MAX,
  LOCK_CODE_MESSAGE,
  LOCK_CODE_MIN,
  LOCK_HASH_PATTERN,
  LOCK_HIDDEN_TEXT,
  LOCK_KINDS,
  LOCK_KIND_MESSAGE,
  LOCK_ONLY_ON_LINKS_MESSAGE,
  LOCK_SALT_PATTERN,
  LOCK_SET_CODE_MESSAGE,
  LOCK_SET_FAILED_MESSAGE,
  LOCK_SHORT_NUMBER_WARNING,
  isLockShape,
  lockCodeError,
  lockCodeWarning,
  lockMarker,
  normalizeLockCode,
  publishLock,
  redactLock,
  type DraftLock,
  type LockKind,
  type PublishedLock,
} from "./lock";
export {
  REDIRECT_GONE_MESSAGE,
  REDIRECT_LABEL_MAX,
  REDIRECT_LOCKED_MESSAGE,
  REDIRECT_LOOP_MESSAGE,
  REDIRECT_PICK_MESSAGE,
  isEligibleRedirectLink,
  redirectOptions,
  redirectTargetIssue,
  type RedirectOption,
} from "./redirect";
